blog/urls.py
from django.urls import path
from django.conf.urls import url


from . import views

urlpatterns=[
	path('',views.hello,name='hello'),
	path('time/',views.current_datetime,name='current_datetime'),
	url(r'^time/(\d{1,2})$',views.hours_ahead,name='hours_ahead'),
	# url(r'^time/plus/(d{1,2})/$', 'blog.views.hours_ahead'),
	path('index/',views.index,name='index'),


	url(r'^article/(?P<article_id>[0-9]+)$',views.article_page,name='article_page'),

	# url(r'^edit/$',views.edit_page,name='edit_page'),
	url(r'^edit/(?P<article_id>[0-9]+)$',views.edit_page,name='edit_page'),
	url(r'^edit/action$',views.edit_action,name='edit_action'),
]

blog2/urls.py
from django.urls import path
from django.conf.urls import url


from . import views

urlpatterns=[
	path('index/',views.index,name='index'),
]

my_django/urls.py
from django.contrib import admin
from django.urls import path,include

# from blog.views import hello
# from blog.views import current_datetime

from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('hello/',hello),
    # path('time/',current_datetime),
    # path(r'time/',current_datetime),

    # path('blog/', include('blog.urls')),


    # url(r'blog/', include('blog.urls')),
    # django2.0的写法
    path('blog/', include(('blog.urls','blog'),namespace = 'blog')),
    url(r'blog2/', include('blog2.urls')),
]

blog/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
	"""docstring for Question"""
	# def __init__(self, arg):
	# 	super(Question, self).__init__()
	# 	self.arg = arg

	question_text=models.CharField(max_length=200)
	pub_date=models.DateTimeField('date published')
		
class Choice(models.Model):
	"""docstring for Choice"""
	# def __init__(self, arg):
	# 	super(Choice, self).__init__()
	# 	self.arg = arg

	question=models.ForeignKey(Question,on_delete=models.CASCADE)
	choice_text=models.CharField(max_length=200)
	votes=models.IntegerField(default=0)
		
# 建立数据模型 然后生成数据表
# 命令行中进入manage.py同级目录
# 执行python manage.py makemigrations app名（可选）
# 再执行python manage.py migrate
# django会自动在app/migrations/目录下生成移植文件

# 然后可以查看sql命令
# 执行python manage.py sqlmigrate 应用名 文件id查看sql语句
# python manage.py sqlmigrate blog 0002_article
class Article(models.Model):
	"""docstring for Article"""

	title=models.CharField(max_length=32,default='Title')
	content=models.TextField(null=True)
	# pub_time=models.DateTimeField(auto_now=True)
	pub_time=models.DateTimeField(null=True)

	def __str__(self):
		return self.title

		

blog2/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse,Http404
import datetime

from . import models

# Create your views here.

def hello(request):
	return HttpResponse('<html>hello world</html>')

def current_datetime(request):
	now=datetime.datetime.now()
	html="<html><body>It is now %s.</body></html>" % now
	return HttpResponse(html)

def hours_ahead(request,offset):
   try:  
       offset = int(offset)
   except ValueError:  
       raise Http404()  
   dt= datetime.datetime.now() + datetime.timedelta(hours=offset)
   html = "<html><body>In %s hour(s), it will be%s.</body></html>" % (offset, dt)  
   return HttpResponse(html)

def index(request):
	# return render(request,'blog/index.html',{'hello':'xixi'})

	# article=models.Article.objects.get(pk=1)
	# return render(request,'blog/index.html',{'article':article})

	articles=models.Article.objects.all()
	return render(request,'blog/index.html',{'articles':articles})



def article_page(request,article_id):
	article=models.Article.objects.get(pk=article_id)
	return render(request,'blog/article_page.html',{'article':article})


# def edit_page(request):
# 	return render(request,'blog/edit_page.html')

def edit_page(request,article_id):
	if str(article_id)=='0':
		return render(request,'blog/edit_page.html')
	article=models.Article.objects.get(pk=article_id)
	return render(request,'blog/edit_page.html',{'article':article})
	

	


# def edit_action(request):
# 	title=request.POST.get('title','Title')
# 	content=request.POST.get('content','CONTENT')
# 	models.Article.objects.create(title=title,content=content)
# 	articles=models.Article.objects.all()
# 	return render(request,'blog/index.html',{'articles':articles})

def edit_action(request):
	title=request.POST.get('title','Title')
	content=request.POST.get('content','CONTENT')
	article_id=request.POST.get('article_id','0')
	if article_id=='0':
		models.Article.objects.create(title=title,content=content)
		articles=models.Article.objects.all()
		return render(request,'blog/index.html',{'articles':articles})

	article=models.Article.objects.get(pk=article_id)
	article.title=title
	article.content=content
	article.save()
	return render(request,'blog/article_page.html',{'article':article})

blog2/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
	return render(request,'blog2/index.html')

blog/templates/blog/article_page.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Article Page</title>
</head>
<body>
	<h1>{{article.title}}</h1>
	<br>
	<h3>{{article.content}}</h3>
	<br><br>
	<a href="{% url 'blog:edit_page' article.id %}">修改文章</a>
</body>
</html>

blog/templates/blog/edit_page.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>修改页面</title>
</head>
<body>
	<form action="{% url 'blog:edit_action' %}" method="post">

		{% csrf_token %}

		<!-- 方案一 使用if else 方式 -->
		<!-- {% if article %}
		<input type="hidden" name="article_id" value="{{article.id}}">
		<label>文章标题
			<input type="text" name="title" value="{{article.title}}">
		</label>
		<br>
		<label>文章内容
			<input type="text" name="content" value="{{article.content}}">
		</label>
		<br>
		{% else %}
		<input type="hidden" name="article_id" value="0">
		<label>文章标题
			<input type="text" name="title">
		</label>
		<br>
		<label>文章内容
			<input type="text" name="content">
		</label>
		<br>
		{% endif %}

		<input type="submit" value="提交"> -->

		<!-- 方案二 使用过滤器的方式 设置默认值为0 -->
		<input type="hidden" name="article_id" value="{{article.id | default:'0'}}">
		<label>文章标题
			<input type="text" name="title" value="{{article.title}}">
		</label>
		<br>
		<label>文章内容
			<input type="text" name="content" value="{{article.content}}">
		</label>
		<br>

		<input type="submit" value="提交">
	</form>
	
</body>
</html>

blog/templates/blog/index.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>test</title>
</head>
<body>
	<!-- <h1>你好 世界  {{hello}}</h1> -->

<!-- 	<h1>你好 世界  标题：{{article.title}}</h1>
	<h1>内容：  {{article.content}}</h1> -->

<h3><a href="{% url 'blog:edit_page' 0 %}">新文章</a></h3>

	{% for article in articles %}
		<a href="{% url 'blog:article_page' article.id %}">{{article.title}}</a>
		<br>
	{% endfor %}
</body>
</html>

blog2/templates/blog2/index.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>test2</title>
</head>
<body>
	<h1>你好 世界222  </h1>
</body>
</html>